model_list:
  - model_name: <your_model_alias>
    litellm_params:
      model: <your_model_name>
      api_key: <your_provider_api_key>

general_settings:
  database_url: "postgres://<db_user>:<db_password>@<db_host>:<db_port>/<db_name>"
  master_key: <your_master_key>
